#include "unity.h"
#include "LED.h"

void test_LED_Init_Should_SetLEDsAsGPIO(void)
{
	LED_PINSEL=BIT_TO_MASK(LED_18_BIT) | BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT);

	LED_Init();

	TEST_ASSERT_EQUAL_HEX32( 0xFFFF30CF,LED_PINSEL);
}

void test_LED_Init_Should_SetLEDsToEnableIO(void)
{
	LED_PORT->FIOMASK= BIT_TO_MASK(LED_18_BIT) | BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT);

	LED_Init();

	TEST_ASSERT_EQUAL_HEX32( 0xFF4BFFFF,LED_PORT->FIOMASK);
}

void test_LED_Init_Should_SetLEDsASOutputs(void)
{
	LED_PORT->FIODIR= ~(BIT_TO_MASK(LED_18_BIT) | BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT) );

	LED_Init();

	TEST_ASSERT_EQUAL_HEX32( 0xB40000,LED_PORT->FIODIR);
}

void test_LED_Init_Should_SetPulldownsForTheseLEDs(void)
{
	LED_PINMODE = LED_PIN_BIT(LED_18_BIT) | LED_PIN_BIT(LED_20_BIT) | LED_PIN_BIT(LED_21_BIT) | LED_PIN_BIT(LED_23_BIT);

	LED_Init();

	TEST_ASSERT_EQUAL_HEX32( 0xFFFF30CF,LED_PINMODE);
}

void test_LED_Init_Should_SetHighLED1AndSetLowOtherLEDs(void)
{
	LED_PORT->FIOSET= ~BIT_TO_MASK(LED_18_BIT);
	LED_PORT->FIOCLR= ~( BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT) );

	LED_Init();

	TEST_ASSERT_EQUAL_HEX32(0x40000,LED_PORT->FIOSET);
	TEST_ASSERT_EQUAL_HEX32(0xB00000,LED_PORT->FIOCLR);
}

