#include "LED.h"

void LED_Init(void)
{
	// set low LED-pins to GPIO
	LED_PINSEL= ~( LED_PIN_BIT(LED_0_BIT) | LED_PIN_BIT(LED_1_BIT) | LED_PIN_BIT(LED_2_BIT) | LED_PIN_BIT(LED_3_BIT));

	// enable IO on these pins
	LED_PORT->FIOMASK= ~(BIT_TO_MASK(LED_0_BIT) | BIT_TO_MASK(LED_1_BIT) | BIT_TO_MASK(LED_2_BIT) | BIT_TO_MASK(LED_3_BIT));

	// enable LED-pins as outputs
	LED_PORT->FIODIR= BIT_TO_MASK(LED_0_BIT) | BIT_TO_MASK(LED_1_BIT) | BIT_TO_MASK(LED_2_BIT) | BIT_TO_MASK(LED_3_BIT);

	// enable pulldowns for these LEDs
	LED_PINMODE = ~( LED_PIN_BIT(LED_0_BIT) | LED_PIN_BIT(LED_1_BIT) | LED_PIN_BIT(LED_2_BIT) | LED_PIN_BIT(LED_3_BIT));

	// Set high LED18 and set low others LEDs
	LED_PORT->FIOSET= BIT_TO_MASK(LED_0_BIT);
	LED_PORT->FIOCLR=  BIT_TO_MASK(LED_1_BIT) | BIT_TO_MASK(LED_2_BIT) | BIT_TO_MASK(LED_3_BIT);

}
