#include "LED.h"

void LED_Init(void)
{
	// set low LED-pins to GPIO
	LED_PINSEL= ~( LED_PIN_BIT(LED_18_BIT) | LED_PIN_BIT(LED_20_BIT) | LED_PIN_BIT(LED_21_BIT) | LED_PIN_BIT(LED_23_BIT));

	// enable IO on these pins
	LED_PORT->FIOMASK= ~(BIT_TO_MASK(LED_18_BIT) | BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT));

	// enable LED-pins as outputs
	LED_PORT->FIODIR= BIT_TO_MASK(LED_18_BIT) | BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT);

	// enable pulldowns for these LEDs
	LED_PINMODE = ~( LED_PIN_BIT(LED_18_BIT) | LED_PIN_BIT(LED_20_BIT) | LED_PIN_BIT(LED_21_BIT) | LED_PIN_BIT(LED_23_BIT));

	// Set high LED18 and set low others LEDs
	LED_PORT->FIOSET= BIT_TO_MASK(LED_18_BIT);
	LED_PORT->FIOCLR=  BIT_TO_MASK(LED_20_BIT) | BIT_TO_MASK(LED_21_BIT) | BIT_TO_MASK(LED_23_BIT);

}
